name: deepdisc

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - astropy
  - ipykernel
  - imgaug
  - numpy
  - opencv
  - pybind11
  - pip:
    - autograd
    - peigen
    - proxmin
    - timm