name: deepdisc

channels:
  - conda-forge
  - defaults

dependencies:
  - numpy>=2.0
  - astropy>=6.1.0
  - scipy 
  - pybind11
  - pip:
    - autograd
    - peigen
    - proxmin
    - timm