name: deepdiscnv
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy>=2.0
  - astropy>=6.1.0
  - scipy
  - pybind11
  - pip
  - pip:
      - autograd
      - peigen
      - proxmin
      - timm