name: deepdiscnv
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - astropy
  - scipy
  - pybind11
  - pip
  - pip:
      - autograd
      - peigen
      - proxmin
      - timm
      - opencv-python